import unittest
from CousinsMarriageValidation import check_whether_first_cousins_married

class TestCousinMarrages(unittest.TestCase):
    def setUp(self):
        self.parsed_file2 = { 'family': {'@F8@': {'Children': {'@I23@', '@I25@', '@I27@', '@I31@'},
                                          'Spouse 1': '@I24@',
                                          'Spouse 2': '@I7@',
                                          'Married': '21 FEB 1984',
                                          'Divorced': '2 DEC 2007',
                                          'Spouse 1 Name': 'Cliff /Richards/',
                                          'Spouse 2 Name': 'Sondra /Huxtable/'},
                                         '@F9@': {'Children': {'@I51@'},
                                          'Spouse 1': '@I26@',
                                          'Spouse 2': '@I25@',
                                          'Married': '2 JUL 1988',
                                          'Spouse 1 Name': 'Jack /Daniels/',
                                          'Spouse 2 Name': 'Mary /Richards/',
                                          'Divorced': 'NA'},
                                         '@F10@': {'Children': {'@I52@'},
                                          'Spouse 1': '@I27@',
                                          'Spouse 2': '@I28@',
                                          'Married': '1 AUG 2016',
                                          'Divorced': '30 SEP 2014',
                                          'Spouse 1 Name': 'Skyler /Richards/',
                                          'Spouse 2 Name': 'Sarah /Sanders/'},
                                         '@F11@': {'Children': 'NA',
                                          'Spouse 1': '@I40@',
                                          'Spouse 2': '@I38@',
                                          'Married': '22 APR 2018',
                                          'Spouse 1 Name': 'Harper /Smith/',
                                          'Spouse 2 Name': 'Carly /Smith/',
                                          'Divorced': 'NA'},
                                         '@F12@': {'Children': 'NA',
                                          'Spouse 1': '@I31@',
                                          'Spouse 2': '@I7@',
                                          'Married': '7 DEC 2006',
                                          'Spouse 1 Name': 'Bucky /Richards/',
                                          'Spouse 2 Name': 'Sondra /Huxtable/',
                                          'Divorced': 'NA'},
                                         '@F13@': {'Children': 'NA',
                                          'Spouse 1': '@I51@',
                                          'Spouse 2': '@I52@',
                                          'Married': '21 FEB 1985',
                                          'Divorced': 'NA',
                                          'Spouse 1 Name': 'Son of Jack Daniels & Mary Richards',
                                          'Spouse 2 Name': 'Daughter of Skyer Richards & Sarah Sanders'} 
                                          },
                'members' : {'@I1@': {'ID': '@I1@',
                              'Child': {'@F1@'},
                              'Spouse': 'NA',
                              'Name': 'George /Tesla/',
                              'Gender': 'M',
                              'Birthday': '2 JAN 1982',
                              'Death': 'NA',
                              'Alive?': 'Y',
                              'Age': 37},
                             '@I1@_2 DUPLICATE ID': {'ID': '@I1@_2 DUPLICATE ID',
                              'Child': {'@F1@'},
                              'Spouse': 'NA',
                              'Name': 'Gage /Smith/',
                              'Gender': 'M',
                              'Birthday': '2 JAN 1982',
                              'Death': 'NA',
                              'Alive?': 'Y',
                              'Age': 37},
                             '@I3@': {'ID': '@I3@',
                              'Child': {'@F1@'},
                              'Spouse': 'NA',
                              'Name': 'Gregory /Smith/',
                              'Gender': 'M',
                              'Birthday': '?? OCT 1984',
                              'Death': 'NA',
                              'Alive?': 'Y',
                              'Age': 'Unknown'},
                             '@I4@': {'ID': '@I4@',
                              'Child': 'NA',
                              'Spouse': {'@F1@', '@F2@'},
                              'Name': 'Brian /Smith/',
                              'Gender': 'M',
                              'Birthday': '21 SEP 1756',
                              'Death': 'NA',
                              'Alive?': 'Y',
                              'Age': 262},
                             '@I5@': {'ID': '@I5@',
                              'Child': 'NA',
                              'Spouse': {'@F2@'},
                              'Name': 'Jane Lancing /Smith/',
                              'Gender': 'F',
                              'Birthday': '31 APR 1959',
                              'Death': 'NA',
                              'Alive?': 'Y',
                              'Age': 60},
                             '@I6@': {'ID': '@I6@',
                              'Child': {'@F3@'},
                              'Spouse': {'@F1@'},
                              'Name': 'Rebecca /Bellini/',
                              'Gender': 'F',
                              'Birthday': '13 MAY 1960',
                              'Death': 'NA',
                              'Alive?': 'Y',
                              'Age': 58},
                             '@I7@': {'ID': '@I7@',
                              'Child': {'@F3@'},
                              'Spouse': {'@F12@', '@F8@'},
                              'Name': 'Sondra /Huxtable/',
                              'Gender': 'F',
                              'Birthday': '17 MAY 1960',
                              'Death': 'NA',
                              'Alive?': 'Y',
                              'Age': 58},
                             '@I8@': {'ID': '@I8@',
                              'Child': {'@F2@'},
                              'Spouse': 'NA',
                              'Name': 'Jason /Smith/',
                              'Gender': 'M',
                              'Birthday': '15 AUG 1990',
                              'Death': 'NA',
                              'Alive?': 'Y',
                              'Age': 28},
                             '@I9@': {'ID': '@I9@',
                              'Child': {'@F2@'},
                              'Spouse': 'NA',
                              'Name': 'Jackson /Smith/',
                              'Gender': 'M',
                              'Birthday': '15 AUG 1990',
                              'Death': 'NA',
                              'Alive?': 'Y',
                              'Age': 28},
                             '@I10@': {'ID': '@I10@',
                              'Child': {'@F2@'},
                              'Spouse': {'@F4@', '@F5@'},
                              'Name': 'Jasmine /Smith/',
                              'Gender': 'F',
                              'Birthday': '15 AUG 1990',
                              'Death': 'NA',
                              'Alive?': 'Y',
                              'Age': 28},
                             '@I11@': {'ID': '@I11@',
                              'Child': {'@F2@'},
                              'Spouse': 'NA',
                              'Name': 'Jamie /Smith/',
                              'Gender': 'F',
                              'Birthday': '15 AUG 1990',
                              'Death': 'NA',
                              'Alive?': 'Y',
                              'Age': 28},
                             '@I12@': {'ID': '@I12@',
                              'Child': {'@F2@'},
                              'Spouse': 'NA',
                              'Name': 'Joel /Smith/',
                              'Gender': 'M',
                              'Birthday': '15 AUG 1990',
                              'Death': 'NA',
                              'Alive?': 'Y',
                              'Age': 28},
                             '@I13@': {'ID': '@I13@',
                              'Child': {'@F2@'},
                              'Spouse': 'NA',
                              'Name': 'Joel /Smith/',
                              'Gender': 'M',
                              'Birthday': '15 AUG 1990',
                              'Death': 'NA',
                              'Alive?': 'Y',
                              'Age': 28},
                             '@I14@': {'ID': '@I14@',
                              'Child': {'@F6@'},
                              'Spouse': {'@F3@'},
                              'Name': 'Michael Jr /Bellini/',
                              'Gender': 'M',
                              'Birthday': '5 JUN 1945',
                              'Death': '19 APR 1985',
                              'Alive?': 'N',
                              'Age': 39},
                             '@I15@': {'ID': '@I15@',
                              'Child': 'NA',
                              'Spouse': {'@F3@'},
                              'Name': 'Luanne /Scott/',
                              'Gender': 'F',
                              'Birthday': '22 DEC 1949',
                              'Death': 'NA',
                              'Alive?': 'Y',
                              'Age': 69},
                             '@I16@': {'ID': '@I16@',
                              'Child': {'@F3@'},
                              'Spouse': 'NA',
                              'Name': 'Braxton /Bellini/',
                              'Gender': 'M',
                              'Birthday': '18 FEB 1986',
                              'Death': '13 MAY 1984',
                              'Alive?': 'N',
                              'Age': -2},
                             '@I17@': {'ID': '@I17@',
                              'Child': 'NA',
                              'Spouse': {'@F6@'},
                              'Name': 'Michael Joseph /Bellini/',
                              'Gender': 'M',
                              'Birthday': '21 JUL 1920',
                              'Death': '21 JUL 1999',
                              'Alive?': 'N',
                              'Age': 79},
                             '@I18@': {'ID': '@I18@',
                              'Child': 'NA',
                              'Spouse': {'@F6@'},
                              'Name': 'Louisa Maria /DelCuore/',
                              'Gender': 'F',
                              'Birthday': '3 OCT 1922',
                              'Death': '19 SEP 2001',
                              'Alive?': 'N',
                              'Age': 78},
                             '@I19@': {'ID': '@I19@',
                              'Child': 'NA',
                              'Spouse': {'@F7@'},
                              'Name': 'Sonia /Gutierrez/',
                              'Gender': 'F',
                              'Birthday': '2 APR 1933',
                              'Death': '19 SEP 2010',
                              'Alive?': 'N',
                              'Age': 77},
                             '@I20@': {'ID': '@I20@',
                              'Child': 'NA',
                              'Spouse': {'@F7@'},
                              'Name': 'Enrique /Martinez/',
                              'Gender': 'M',
                              'Birthday': '17 APR 1932',
                              'Death': '2 NOV 2013',
                              'Alive?': 'N',
                              'Age': 81},
                             '@I21@': {'ID': '@I21@',
                              'Child': {'@F7@'},
                              'Spouse': 'NA',
                              'Name': 'Gilbert /Martinez/',
                              'Gender': 'M',
                              'Birthday': '30 APR 2002',
                              'Death': 'NA',
                              'Alive?': 'Y',
                              'Age': 16},
                             '@I22@': {'ID': '@I22@',
                              'Child': {'@F7@'},
                              'Spouse': 'NA',
                              'Name': 'Jenny /Martinez/',
                              'Gender': 'F',
                              'Birthday': '15 JUL 2011',
                              'Death': 'NA',
                              'Alive?': 'Y',
                              'Age': 7},
                             '@I23@': {'ID': '@I23@',
                              'Child': {'@F8@'},
                              'Spouse': 'NA',
                              'Name': 'Kenny /Richards/',
                              'Gender': 'M',
                              'Birthday': '5 DEC 2019',
                              'Death': 'NA',
                              'Alive?': 'Y',
                              'Age': -1},
                             '@I24@': {'ID': '@I24@',
                              'Child': 'NA',
                              'Spouse': {'@F8@'},
                              'Name': 'Cliff /Richards/',
                              'Gender': 'M',
                              'Birthday': '3 SEP 1959',
                              'Death': '19 MAR 2004',
                              'Alive?': 'N',
                              'Age': 44},
                             '@I25@': {'ID': '@I25@',
                              'Child': {'@F8@'},
                              'Spouse': {'@F9@'},
                              'Name': 'Mary /Richards/',
                              'Gender': 'F',
                              'Birthday': '4 AUG 1990',
                              'Death': 'NA',
                              'Alive?': 'Y',
                              'Age': 28},
                             '@I26@': {'ID': '@I26@',
                              'Child': 'NA',
                              'Spouse': {'@F9@'},
                              'Name': 'Jack /Daniels/',
                              'Gender': 'M',
                              'Birthday': '4 FEB 1991',
                              'Death': 'NA',
                              'Alive?': 'Y',
                              'Age': 28},
                             '@I27@': {'ID': '@I27@',
                              'Child': {'@F8@'},
                              'Spouse': {'@F10@'},
                              'Name': 'Skyler /Richards/',
                              'Gender': 'M',
                              'Birthday': '24 JAN 1993',
                              'Death': 'NA',
                              'Alive?': 'Y',
                              'Age': 26},
                             '@I28@': {'ID': '@I28@',
                              'Child': 'NA',
                              'Spouse': {'@F10@'},
                              'Name': 'Sarah /Sanders/',
                              'Gender': 'F',
                              'Birthday': '25 FEB 1990',
                              'Death': 'NA',
                              'Alive?': 'Y',
                              'Age': 29},
                             '@I29@': {'ID': '@I29@',
                              'Child': 'NA',
                              'Spouse': {'@F5@'},
                              'Name': 'Matthew /Collins/',
                              'Gender': 'M',
                              'Birthday': '3 MAR 1986',
                              'Death': 'NA',
                              'Alive?': 'Y',
                              'Age': 33},
                             '@I30@': {'ID': '@I30@',
                              'Child': 'NA',
                              'Spouse': {'@F4@'},
                              'Name': 'Samuel /Jackson/',
                              'Gender': 'M',
                              'Birthday': '28 FEB 1992',
                              'Death': 'NA',
                              'Alive?': 'Y',
                              'Age': 27},
                             '@I31@': {'ID': '@I31@',
                              'Child': {'@F8@'},
                              'Spouse': {'@F12@'},
                              'Name': 'Bucky /Richards/',
                              'Gender': 'M',
                              'Birthday': '2 APR 1989',
                              'Death': 'NA',
                              'Alive?': 'Y',
                              'Age': 30},
                             '@I32@': {'ID': '@I32@',
                              'Child': {'@F2@'},
                              'Spouse': 'NA',
                              'Name': 'John /Smith/',
                              'Gender': 'M',
                              'Birthday': '10 FEB 1992',
                              'Death': 'NA',
                              'Alive?': 'Y',
                              'Age': 27},
                             '@I33@': {'ID': '@I33@',
                              'Child': {'@F2@'},
                              'Spouse': 'NA',
                              'Name': 'Jessie /Smith/',
                              'Gender': 'F',
                              'Birthday': '9 APR 1994',
                              'Death': 'NA',
                              'Alive?': 'Y',
                              'Age': 24},
                             '@I34@': {'ID': '@I34@',
                              'Child': {'@F2@'},
                              'Spouse': 'NA',
                              'Name': 'Kyle /Smith/',
                              'Gender': 'M',
                              'Birthday': '4 APR 1988',
                              'Death': 'NA',
                              'Alive?': 'Y',
                              'Age': 31},
                             '@I35@': {'ID': '@I35@',
                              'Child': {'@F2@'},
                              'Spouse': 'NA',
                              'Name': 'Mark /Smith/',
                              'Gender': 'M',
                              'Birthday': '4 APR 1988',
                              'Death': 'NA',
                              'Alive?': 'Y',
                              'Age': 31},
                             '@I36@': {'ID': '@I36@',
                              'Child': {'@F2@'},
                              'Spouse': 'NA',
                              'Name': 'Journey /Smith/',
                              'Gender': 'F',
                              'Birthday': '4 APR 1988',
                              'Death': 'NA',
                              'Alive?': 'Y',
                              'Age': 31},
                             '@I37@': {'ID': '@I37@',
                              'Child': {'@F2@'},
                              'Spouse': 'NA',
                              'Name': 'Roger /Smith/',
                              'Gender': 'M',
                              'Birthday': '4 MAR 1986',
                              'Death': 'NA',
                              'Alive?': 'Y',
                              'Age': 33},
                             '@I38@': {'ID': '@I38@',
                              'Child': {'@F2@'},
                              'Spouse': {'@F11@'},
                              'Name': 'Carly /Smith/',
                              'Gender': 'F',
                              'Birthday': '3 AUG 1996',
                              'Death': 'NA',
                              'Alive?': 'Y',
                              'Age': 22},
                             '@I39@': {'ID': '@I39@',
                              'Child': {'@F2@'},
                              'Spouse': 'NA',
                              'Name': 'Beau /Smith/',
                              'Gender': 'M',
                              'Birthday': '20 MAY 1994',
                              'Death': 'NA',
                              'Alive?': 'Y',
                              'Age': 24},
                             '@I40@': {'ID': '@I40@',
                              'Child': {'@F2@'},
                              'Spouse': {'@F11@'},
                              'Name': 'Harper /Smith/',
                              'Gender': 'M',
                              'Birthday': '7 SEP 1999',
                              'Death': 'NA',
                              'Alive?': 'Y',
                              'Age': 19},
                             '@I41@': {'ID': '@I41@',
                              'Child': {'@F2@'},
                              'Spouse': 'NA',
                              'Name': 'Tony /Smith/',
                              'Gender': 'M',
                              'Birthday': '5 OCT 2001',
                              'Death': 'NA',
                              'Alive?': 'Y',
                              'Age': 17},
                             '@I51@': {'ID': '@I51@',
                              'Child': {'@F9@'},
                              'Spouse': {'@F13@'},
                              'Name': 'Son of Jack Daniels & Mary Richards',
                              'Gender': 'M',
                              'Birthday': '24 JAN 1995',
                              'Death': 'NA',
                              'Alive?': 'Y',
                              'Age': 26},
                             '@I52@': {'ID': '@I52@',
                              'Child': {'@F10@'},
                              'Spouse': {'@F13@'},
                              'Name': 'Daughter of Skyer Richards & Sarah Sanders',
                              'Gender': 'F',
                              'Birthday': '24 JAN 1993',
                              'Death': 'NA',
                              'Alive?': 'Y',
                              'Age': 26}}              
                }
        self.parsed_file1 = {'family': {'@F1@': {'Children': {'@I1@', '@I3@'},
                           'Spouse 1': '@I4@',
                           'Spouse 2': '@I6@',
                           'Married': '15 MAR 1982',
                           'Spouse 1 Name': 'Brian /Smith/',
                           'Spouse 2 Name': 'Rebecca /Bellini/',
                           'Divorced': 'NA'},
                          '@F2@': {'Children': {'@I10@',
                            '@I11@',
                            '@I12@',
                            '@I13@',
                            '@I32@',
                            '@I33@',
                            '@I34@',
                            '@I35@',
                            '@I36@',
                            '@I37@',
                            '@I38@',
                            '@I39@',
                            '@I40@',
                            '@I41@',
                            '@I8@',
                            '@I9@'},
                           'Spouse 1': '@I4@',
                           'Spouse 2': '@I5@',
                           'Married': '4 JUL 1990',
                           'Spouse 1 Name': 'Brian /Smith/',
                           'Spouse 2 Name': 'Jane Lancing /Smith/',
                           'Divorced': 'NA'},
                          '@F3@': {'Children': {'@I16@', '@I6@', '@I7@'},
                           'Spouse 1': '@I14@',
                           'Spouse 2': '@I15@',
                           'Married': '17 APR 1968',
                           'Spouse 1 Name': 'Michael Jr /Bellini/',
                           'Spouse 2 Name': 'Luanne /Scott/',
                           'Divorced': 'NA'},
                          '@F4@': {'Children': 'NA',
                           'Spouse 1': '@I30@',
                           'Spouse 2': '@I10@',
                           'Married': '3 MAY 2005',
                           'Spouse 1 Name': 'Samuel /Jackson/',
                           'Spouse 2 Name': 'Jasmine /Smith/',
                           'Divorced': 'NA'},
                          '@F5@': {'Children': 'NA',
                           'Spouse 1': '@I29@',
                           'Spouse 2': '@I10@',
                           'Married': '5 FEB 2003',
                           'Spouse 1 Name': 'Matthew /Collins/',
                           'Spouse 2 Name': 'Jasmine /Smith/',
                           'Divorced': 'NA'},
                          '@F6@': {'Children': {'@I14@'},
                           'Spouse 1': '@I17@',
                           'Spouse 2': '@I18@',
                           'Married': '9 JUL 2000',
                           'Spouse 1 Name': 'Michael Joseph /Bellini/',
                           'Spouse 2 Name': 'Louisa Maria /DelCuore/',
                           'Divorced': 'NA'},
                          '@F7@': {'Children': {'@I21@', '@I22@'},
                           'Spouse 1': '@I20@',
                           'Spouse 2': '@I19@',
                           'Married': '28 AUG 1949',
                           'Spouse 1 Name': 'Enrique /Martinez/',
                           'Spouse 2 Name': 'Sonia /Gutierrez/',
                           'Divorced': 'NA'},
                          '@F8@': {'Children': {'@I23@', '@I25@', '@I27@', '@I31@'},
                           'Spouse 1': '@I24@',
                           'Spouse 2': '@I7@',
                           'Married': '21 FEB 1984',
                           'Divorced': '2 DEC 2007',
                           'Spouse 1 Name': 'Cliff /Richards/',
                           'Spouse 2 Name': 'Sondra /Huxtable/'},
                          '@F9@': {'Children': 'NA',
                           'Spouse 1': '@I26@',
                           'Spouse 2': '@I25@',
                           'Married': '2 JUL 1988',
                           'Spouse 1 Name': 'Jack /Daniels/',
                           'Spouse 2 Name': 'Mary /Richards/',
                           'Divorced': 'NA'},
                          '@F10@': {'Children': 'NA',
                           'Spouse 1': '@I27@',
                           'Spouse 2': '@I28@',
                           'Married': '1 AUG 2016',
                           'Divorced': '30 SEP 2014',
                           'Spouse 1 Name': 'Skyler /Richards/',
                           'Spouse 2 Name': 'Sarah /Sanders/'},
                          '@F11@': {'Children': 'NA',
                           'Spouse 1': '@I40@',
                           'Spouse 2': '@I38@',
                           'Married': '22 APR 2018',
                           'Spouse 1 Name': 'Harper /Smith/',
                           'Spouse 2 Name': 'Carly /Smith/',
                           'Divorced': 'NA'},
                          '@F12@': {'Children': 'NA',
                           'Spouse 1': '@I31@',
                           'Spouse 2': '@I7@',
                           'Married': '7 DEC 2006',
                           'Spouse 1 Name': 'Bucky /Richards/',
                           'Spouse 2 Name': 'Sondra /Huxtable/',
                           'Divorced': 'NA'}},
                         'members': {'@I1@': {'ID': '@I1@',
                           'Child': {'@F1@'},
                           'Spouse': 'NA',
                           'Name': 'George /Tesla/',
                           'Gender': 'M',
                           'Birthday': '2 JAN 1982',
                           'Death': 'NA',
                           'Alive?': 'Y',
                           'Age': 37},
                          '@I1@_2 DUPLICATE ID': {'ID': '@I1@_2 DUPLICATE ID',
                           'Child': {'@F1@'},
                           'Spouse': 'NA',
                           'Name': 'Gage /Smith/',
                           'Gender': 'M',
                           'Birthday': '2 JAN 1982',
                           'Death': 'NA',
                           'Alive?': 'Y',
                           'Age': 37},
                          '@I3@': {'ID': '@I3@',
                           'Child': {'@F1@'},
                           'Spouse': 'NA',
                           'Name': 'Gregory /Smith/',
                           'Gender': 'M',
                           'Birthday': '?? OCT 1984',
                           'Death': 'NA',
                           'Alive?': 'Y',
                           'Age': 'Unknown'},
                          '@I4@': {'ID': '@I4@',
                           'Child': 'NA',
                           'Spouse': {'@F1@', '@F2@'},
                           'Name': 'Brian /Smith/',
                           'Gender': 'M',
                           'Birthday': '21 SEP 1756',
                           'Death': 'NA',
                           'Alive?': 'Y',
                           'Age': 262},
                          '@I5@': {'ID': '@I5@',
                           'Child': 'NA',
                           'Spouse': {'@F2@'},
                           'Name': 'Jane Lancing /Smith/',
                           'Gender': 'F',
                           'Birthday': '31 APR 1959',
                           'Death': 'NA',
                           'Alive?': 'Y',
                           'Age': 60},
                          '@I6@': {'ID': '@I6@',
                           'Child': {'@F3@'},
                           'Spouse': {'@F1@'},
                           'Name': 'Rebecca /Bellini/',
                           'Gender': 'F',
                           'Birthday': '13 MAY 1960',
                           'Death': 'NA',
                           'Alive?': 'Y',
                           'Age': 58},
                          '@I7@': {'ID': '@I7@',
                           'Child': {'@F3@'},
                           'Spouse': {'@F12@', '@F8@'},
                           'Name': 'Sondra /Huxtable/',
                           'Gender': 'F',
                           'Birthday': '17 MAY 1960',
                           'Death': 'NA',
                           'Alive?': 'Y',
                           'Age': 58},
                          '@I8@': {'ID': '@I8@',
                           'Child': {'@F2@'},
                           'Spouse': 'NA',
                           'Name': 'Jason /Smith/',
                           'Gender': 'M',
                           'Birthday': '15 AUG 1990',
                           'Death': 'NA',
                           'Alive?': 'Y',
                           'Age': 28},
                          '@I9@': {'ID': '@I9@',
                           'Child': {'@F2@'},
                           'Spouse': 'NA',
                           'Name': 'Jackson /Smith/',
                           'Gender': 'M',
                           'Birthday': '15 AUG 1990',
                           'Death': 'NA',
                           'Alive?': 'Y',
                           'Age': 28},
                          '@I10@': {'ID': '@I10@',
                           'Child': {'@F2@'},
                           'Spouse': {'@F4@', '@F5@'},
                           'Name': 'Jasmine /Smith/',
                           'Gender': 'F',
                           'Birthday': '15 AUG 1990',
                           'Death': 'NA',
                           'Alive?': 'Y',
                           'Age': 28},
                          '@I11@': {'ID': '@I11@',
                           'Child': {'@F2@'},
                           'Spouse': 'NA',
                           'Name': 'Jamie /Smith/',
                           'Gender': 'F',
                           'Birthday': '15 AUG 1990',
                           'Death': 'NA',
                           'Alive?': 'Y',
                           'Age': 28},
                          '@I12@': {'ID': '@I12@',
                           'Child': {'@F2@'},
                           'Spouse': 'NA',
                           'Name': 'Joel /Smith/',
                           'Gender': 'M',
                           'Birthday': '15 AUG 1990',
                           'Death': 'NA',
                           'Alive?': 'Y',
                           'Age': 28},
                          '@I13@': {'ID': '@I13@',
                           'Child': {'@F2@'},
                           'Spouse': 'NA',
                           'Name': 'Joel /Smith/',
                           'Gender': 'M',
                           'Birthday': '15 AUG 1990',
                           'Death': 'NA',
                           'Alive?': 'Y',
                           'Age': 28},
                          '@I14@': {'ID': '@I14@',
                           'Child': {'@F6@'},
                           'Spouse': {'@F3@'},
                           'Name': 'Michael Jr /Bellini/',
                           'Gender': 'M',
                           'Birthday': '5 JUN 1945',
                           'Death': '19 APR 1985',
                           'Alive?': 'N',
                           'Age': 39},
                          '@I15@': {'ID': '@I15@',
                           'Child': 'NA',
                           'Spouse': {'@F3@'},
                           'Name': 'Luanne /Scott/',
                           'Gender': 'F',
                           'Birthday': '22 DEC 1949',
                           'Death': 'NA',
                           'Alive?': 'Y',
                           'Age': 69},
                          '@I16@': {'ID': '@I16@',
                           'Child': {'@F3@'},
                           'Spouse': 'NA',
                           'Name': 'Braxton /Bellini/',
                           'Gender': 'M',
                           'Birthday': '18 FEB 1986',
                           'Death': '13 MAY 1984',
                           'Alive?': 'N',
                           'Age': -2},
                          '@I17@': {'ID': '@I17@',
                           'Child': 'NA',
                           'Spouse': {'@F6@'},
                           'Name': 'Michael Joseph /Bellini/',
                           'Gender': 'M',
                           'Birthday': '21 JUL 1920',
                           'Death': '21 JUL 1999',
                           'Alive?': 'N',
                           'Age': 79},
                          '@I18@': {'ID': '@I18@',
                           'Child': 'NA',
                           'Spouse': {'@F6@'},
                           'Name': 'Louisa Maria /DelCuore/',
                           'Gender': 'F',
                           'Birthday': '3 OCT 1922',
                           'Death': '19 SEP 2001',
                           'Alive?': 'N',
                           'Age': 78},
                          '@I19@': {'ID': '@I19@',
                           'Child': 'NA',
                           'Spouse': {'@F7@'},
                           'Name': 'Sonia /Gutierrez/',
                           'Gender': 'F',
                           'Birthday': '2 APR 1933',
                           'Death': '19 SEP 2010',
                           'Alive?': 'N',
                           'Age': 77},
                          '@I20@': {'ID': '@I20@',
                           'Child': 'NA',
                           'Spouse': {'@F7@'},
                           'Name': 'Enrique /Martinez/',
                           'Gender': 'M',
                           'Birthday': '17 APR 1932',
                           'Death': '2 NOV 2013',
                           'Alive?': 'N',
                           'Age': 81},
                          '@I21@': {'ID': '@I21@',
                           'Child': {'@F7@'},
                           'Spouse': 'NA',
                           'Name': 'Gilbert /Martinez/',
                           'Gender': 'M',
                           'Birthday': '30 APR 2002',
                           'Death': 'NA',
                           'Alive?': 'Y',
                           'Age': 16},
                          '@I22@': {'ID': '@I22@',
                           'Child': {'@F7@'},
                           'Spouse': 'NA',
                           'Name': 'Jenny /Martinez/',
                           'Gender': 'F',
                           'Birthday': '15 JUL 2011',
                           'Death': 'NA',
                           'Alive?': 'Y',
                           'Age': 7},
                          '@I23@': {'ID': '@I23@',
                           'Child': {'@F8@'},
                           'Spouse': 'NA',
                           'Name': 'Kenny /Richards/',
                           'Gender': 'M',
                           'Birthday': '5 DEC 2019',
                           'Death': 'NA',
                           'Alive?': 'Y',
                           'Age': -1},
                          '@I24@': {'ID': '@I24@',
                           'Child': 'NA',
                           'Spouse': {'@F8@'},
                           'Name': 'Cliff /Richards/',
                           'Gender': 'M',
                           'Birthday': '3 SEP 1959',
                           'Death': '19 MAR 2004',
                           'Alive?': 'N',
                           'Age': 44},
                          '@I25@': {'ID': '@I25@',
                           'Child': {'@F8@'},
                           'Spouse': {'@F9@'},
                           'Name': 'Mary /Richards/',
                           'Gender': 'F',
                           'Birthday': '4 AUG 1990',
                           'Death': 'NA',
                           'Alive?': 'Y',
                           'Age': 28},
                          '@I26@': {'ID': '@I26@',
                           'Child': 'NA',
                           'Spouse': {'@F9@'},
                           'Name': 'Jack /Daniels/',
                           'Gender': 'M',
                           'Birthday': '4 FEB 1991',
                           'Death': 'NA',
                           'Alive?': 'Y',
                           'Age': 28},
                          '@I27@': {'ID': '@I27@',
                           'Child': {'@F8@'},
                           'Spouse': {'@F10@'},
                           'Name': 'Skyler /Richards/',
                           'Gender': 'M',
                           'Birthday': '24 JAN 1993',
                           'Death': 'NA',
                           'Alive?': 'Y',
                           'Age': 26},
                          '@I28@': {'ID': '@I28@',
                           'Child': 'NA',
                           'Spouse': {'@F10@'},
                           'Name': 'Sarah /Sanders/',
                           'Gender': 'F',
                           'Birthday': '25 FEB 1990',
                           'Death': 'NA',
                           'Alive?': 'Y',
                           'Age': 29},
                          '@I29@': {'ID': '@I29@',
                           'Child': 'NA',
                           'Spouse': {'@F5@'},
                           'Name': 'Matthew /Collins/',
                           'Gender': 'M',
                           'Birthday': '3 MAR 1986',
                           'Death': 'NA',
                           'Alive?': 'Y',
                           'Age': 33},
                          '@I30@': {'ID': '@I30@',
                           'Child': 'NA',
                           'Spouse': {'@F4@'},
                           'Name': 'Samuel /Jackson/',
                           'Gender': 'M',
                           'Birthday': '28 FEB 1992',
                           'Death': 'NA',
                           'Alive?': 'Y',
                           'Age': 27},
                          '@I31@': {'ID': '@I31@',
                           'Child': {'@F8@'},
                           'Spouse': {'@F12@'},
                           'Name': 'Bucky /Richards/',
                           'Gender': 'M',
                           'Birthday': '2 APR 1989',
                           'Death': 'NA',
                           'Alive?': 'Y',
                           'Age': 30},
                          '@I32@': {'ID': '@I32@',
                           'Child': {'@F2@'},
                           'Spouse': 'NA',
                           'Name': 'John /Smith/',
                           'Gender': 'M',
                           'Birthday': '10 FEB 1992',
                           'Death': 'NA',
                           'Alive?': 'Y',
                           'Age': 27},
                          '@I33@': {'ID': '@I33@',
                           'Child': {'@F2@'},
                           'Spouse': 'NA',
                           'Name': 'Jessie /Smith/',
                           'Gender': 'F',
                           'Birthday': '9 APR 1994',
                           'Death': 'NA',
                           'Alive?': 'Y',
                           'Age': 24},
                          '@I34@': {'ID': '@I34@',
                           'Child': {'@F2@'},
                           'Spouse': 'NA',
                           'Name': 'Kyle /Smith/',
                           'Gender': 'M',
                           'Birthday': '4 APR 1988',
                           'Death': 'NA',
                           'Alive?': 'Y',
                           'Age': 31},
                          '@I35@': {'ID': '@I35@',
                           'Child': {'@F2@'},
                           'Spouse': 'NA',
                           'Name': 'Mark /Smith/',
                           'Gender': 'M',
                           'Birthday': '4 APR 1988',
                           'Death': 'NA',
                           'Alive?': 'Y',
                           'Age': 31},
                          '@I36@': {'ID': '@I36@',
                           'Child': {'@F2@'},
                           'Spouse': 'NA',
                           'Name': 'Journey /Smith/',
                           'Gender': 'F',
                           'Birthday': '4 APR 1988',
                           'Death': 'NA',
                           'Alive?': 'Y',
                           'Age': 31},
                          '@I37@': {'ID': '@I37@',
                           'Child': {'@F2@'},
                           'Spouse': 'NA',
                           'Name': 'Roger /Smith/',
                           'Gender': 'M',
                           'Birthday': '4 MAR 1986',
                           'Death': 'NA',
                           'Alive?': 'Y',
                           'Age': 33},
                          '@I38@': {'ID': '@I38@',
                           'Child': {'@F2@'},
                           'Spouse': {'@F11@'},
                           'Name': 'Carly /Smith/',
                           'Gender': 'F',
                           'Birthday': '3 AUG 1996',
                           'Death': 'NA',
                           'Alive?': 'Y',
                           'Age': 22},
                          '@I39@': {'ID': '@I39@',
                           'Child': {'@F2@'},
                           'Spouse': 'NA',
                           'Name': 'Beau /Smith/',
                           'Gender': 'M',
                           'Birthday': '20 MAY 1994',
                           'Death': 'NA',
                           'Alive?': 'Y',
                           'Age': 24},
                          '@I40@': {'ID': '@I40@',
                           'Child': {'@F2@'},
                           'Spouse': {'@F11@'},
                           'Name': 'Harper /Smith/',
                           'Gender': 'M',
                           'Birthday': '7 SEP 1999',
                           'Death': 'NA',
                           'Alive?': 'Y',
                           'Age': 19},
                          '@I41@': {'ID': '@I41@',
                           'Child': {'@F2@'},
                           'Spouse': 'NA',
                           'Name': 'Tony /Smith/',
                           'Gender': 'M',
                           'Birthday': '5 OCT 2001',
                           'Death': 'NA',
                           'Alive?': 'Y',
                           'Age': 17}}}
        
    def test_cousins_marriage_positive(self):
        print('US19: Testing for marriage between first cousins (invalid)')
        errors = set()
        check_whether_first_cousins_married(self.parsed_file1, errors)
        self.assertEqual(len(errors), 0, 
                        msg=str([err.getErrMsg() for err in errors]))
    
  
if __name__ == '__main__':
    unittest.main(exit=False, verbosity=2)
